const resources = {
  es: { translation: {
    "nav.home": "Inicio", "nav.blog": "Blog", "nav.writeups": "Writeups", "nav.projects": "Proyectos", "nav.challenges": "Desafíos", "nav.labs": "Academy", "nav.labs.local": "Labs", "nav.hall": "Ranking", "nav.community": "Comunidad", "nav.contact": "Contacto", "nav.portfolio": "Portfolio",
    "menu.open": "Abrir menú", "menu.close": "Cerrar menú", "footer.learning": "Aprendizaje responsable", "footer.privacy": "Privacidad", "footer.terms": "Términos y condiciones", "language.label": "Idioma", "language.es": "Español", "language.en": "English"
  } },
  en: { translation: {
    "nav.home": "Home", "nav.blog": "Blog", "nav.writeups": "Writeups", "nav.projects": "Projects", "nav.challenges": "Challenges", "nav.labs": "Academy", "nav.labs.local": "Labs", "nav.hall": "Ranking", "nav.community": "Community", "nav.contact": "Contact", "nav.portfolio": "Portfolio",
    "menu.open": "Open menu", "menu.close": "Close menu", "footer.learning": "Responsible learning", "footer.privacy": "Privacy", "footer.terms": "Terms and conditions", "language.label": "Language", "language.es": "Español", "language.en": "English"
  } }
};

// Texto editorial local. No se usan servicios externos de traducción ni se envía contenido al navegador.
export const englishText: Record<string, string> = {
  "Aprender la forma": "Learning the shape", "del sistema": "of systems",
  "Trabajo como analista junior de ciberseguridad en": "I work as a junior cybersecurity analyst at",
  ", participo en CJCA y cofundé CyberSecTuc. Acá documento procesos, laboratorios y herramientas que me ayudan a aprender con método y compartir lo que vale la pena.": ", take part in CJCA and co-founded CyberSecTuc. This is where I document processes, labs and tools that help me learn methodically and share what is worth sharing.",
  "FOCO": "FOCUS", "Elastic Stack · detección de intrusiones · seguridad web": "Elastic Stack · intrusion detection · web security",
  "AHORA": "NOW", "aprendizaje continuo hacia red team": "building depth toward red team work",
  "Entrar a c4cker/labs →": "Enter c4cker/labs →", "Leer writeups": "Read writeups",
  "Mi superficie de trabajo": "My working surface", "archivo personal": "personal archive",
  "Cola de práctica": "Practice queue", "Qué estoy preparando": "What I am working on", "Bitácora Markdown": "Markdown notebook", "Abrir writeups →": "Open writeups →",
  "Contacto con": "Contact with", "contexto": "context", "Canales públicos": "Public channels", "Formulario": "Form",
  "Escribirme sin publicar tu correo": "Write to me without publishing your email",
  "Si querés proponer un recurso, señalar una corrección o conversar sobre una colaboración, contame el contexto y el alcance. No envíes secretos, flags ni información sensible.": "If you want to suggest a resource, point out a correction or discuss a collaboration, tell me the context and scope. Do not send secrets, flags or sensitive information.",
  "El formulario se habilita al configurar": "The form is enabled when", "en Cloudflare. Hasta entonces, GitHub y LinkedIn siguen siendo los canales públicos.": "is configured in Cloudflare. Until then, GitHub and LinkedIn remain the public channels.",
  "Canal recomendado": "Recommended channel", "Abrí un issue para una corrección, un recurso nuevo o una colaboración vinculada al sitio.": "Open an issue for a correction, a new resource or a collaboration related to the site.",
  "Abrir repositorio": "Open repository", "Perfil profesional": "Professional profile", "Para una conversación profesional, encontrame también en LinkedIn.": "For a professional conversation, you can also find me on LinkedIn.", "Abrir perfil": "Open profile",
  "Archivo Markdown": "Markdown archive", "Writeups propios,": "My writeups,", "no recetas.": "not recipes.",
  "Cada publicación vive en un archivo Markdown. Las fichas actuales son semillas visuales: reemplazalas por tu evidencia, recorrido y aprendizaje real antes de atribuírtelas.": "Every publication lives in a Markdown file. The current cards are visual seeds: replace them with your evidence, path and real learning before calling them your own.",
  "BUSCADOR DE ARCHIVO": "ARCHIVE SEARCH", "Filtrá por dificultad o buscá por máquina, plataforma o etiqueta.": "Filter by difficulty or search by machine, platform or tag.",
  "Directorio compartido": "Shared directory", "La comunidad es": "Community is", "el mapa, no el ruido.": "the map, not the noise.",
  "Lo que construyo": "What I build", "Herramientas con": "Tools with", "una intención clara.": "a clear purpose.",
  "Práctica local / CTF": "Local practice / CTF", "Desafíos para": "Challenges to", "romper con permiso.": "break with permission.",
  "Entornos aislados": "Isolated environments", "Laboratorios que": "Labs that", "dejan evidencia.": "leave evidence.",
  "Marco de uso": "Terms of use", "Términos y": "Terms and", "condiciones.": "conditions.",
  "Transparencia": "Transparency", "Privacidad": "Privacy", "Leer términos y condiciones": "Read terms and conditions",
  "404 · señal perdida": "404 · lost signal", "No hay evidencia en esta ruta.": "There is no evidence at this route.", "Puede que el enlace haya cambiado o que todavía no exista. Volvé a una zona conocida.": "The link may have changed, or it may not exist yet. Return to a known area.", "Ir al inicio →": "Go home →"
  ,"Bienvenido a un lugar": "Welcome to a place", "para probar en serio": "to practice for real", "Bienvenido a un lugar\n": "Welcome to a place\n",
  "c4cker / laboratorio abierto": "c4cker / open laboratory", "Labs reúne práctica local, laboratorios reproducibles y recursos para convertir curiosidad en método. Empezá por una ruta, leé el alcance y llevá cada prueba a tu propio entorno.": "Labs brings together local practice, reproducible labs and resources to turn curiosity into method. Pick a route, read its scope and run every test in your own environment.",
  "Empezar con un desafío": "Start with a challenge", "Usá únicamente tus equipos, máquinas y servicios autorizados.": "Use only equipment, machines and services you are authorized to test.", "Guía de campo": "Field guide", "Cuatro rutas, una práctica responsable": "Four routes, one responsible practice", "Elegí una puerta y seguí desde ahí.": "Choose a door and continue from there.",
  "Desafíos": "Challenges", "retos para resolver a tu ritmo.": "challenges to solve at your own pace.", "Laboratorios": "Labs", "entornos reproducibles, con su repo a mano.": "reproducible environments, with their repo close by.", "Hall of Fame": "Hall of Fame", "solves semilla y un lugar para dejar tu marca.": "seed solves and a place to leave your mark.", "Recursos, enlaces y gente con quien compartir hallazgos.": "Resources, links and people to share findings with.", "Fuera del laboratorio": "Outside the lab", "La práctica es una parte": "Practice is one part", "del recorrido": "of the journey", "En mi portfolio comparto el trabajo, la formación y las notas que sostienen este espacio.": "My portfolio shares the work, training and notes behind this space.", "Conocer mi portfolio": "Visit my portfolio", "Explorar desafíos": "Explore challenges", "Abrir laboratorios": "Open labs", "Ver el Hall": "View the Hall", "Entrar a comunidad": "Join the community",
  "Entornos aislados": "Isolated environments", "Laboratorios que": "Labs that", "dejan evidencia.": "leave evidence.", "Prácticas vinculadas a retos y writeups. Ejecutalas sin privilegios, en una máquina que controles y con una forma clara de limpiar el entorno.": "Practice linked to challenges and writeups. Run it without privileges, on a machine you control, with a clear cleanup path.", "Cada ficha incluye el repositorio o archivo definitivo del laboratorio.": "Each entry includes the lab's final repository or file.",
  "Registro anónimo": "Anonymous record", "No hay cuentas ni perfiles. El alias se deriva del identificador HMAC generado en el servidor; la IP original no se conserva.": "There are no accounts or profiles. The alias comes from a server-generated HMAC; the original IP is not retained.", "Alias": "Alias", "Desafío": "Challenge", "Resuelto": "Solved", "Mostrando datos semilla mientras no se configure Supabase.": "Showing seed data until Supabase is configured.", "No se pudo actualizar el registro; se mantienen los datos semilla.": "The record could not be updated; seed data remains.",
  "Cada entrada cuenta qué problema intenta resolver, en qué estado está y dónde continuar si querés mirar el material.": "Each entry explains the problem it aims to solve, its current state and where to continue if you want to inspect the material.", "Ver proyecto": "View project", "Qué intento resolver": "What I am trying to solve", "En una línea": "In one line", "Abrir repositorio": "Open repository", "Ir a la sección relacionada": "Go to related section", "Volver a proyectos": "Back to projects",
  "Objetivo verificable": "Verifiable objective", "Publicación segura": "Safe publishing", "Flag obtenida": "Captured flag", "Validar flag": "Validate flag", "¿Con qué nombre querés aparecer?": "What name would you like to use?", "Es opcional. Máximo 32 caracteres; podés usar el nombre que quieras.": "Optional. Maximum 32 characters; use any name you like.", "Tu nickname": "Your nickname", "Guardar nickname": "Save nickname", "Omitir": "Skip", "Flag registrada. Bien hecho.": "Flag registered. Nice work.", "La flag no es válida.": "The flag is not valid.",
  "Directorio compartido": "Shared directory", "Espacios que forman parte de mi recorrido, más referencias para practicar con permiso, investigar mejor y devolver contexto a otras personas.": "Spaces that are part of my journey, plus references for practicing with permission, researching better and sharing context.", "Co-fundador": "Co-founder", "Administrador": "Administrator", "Unirme a CyberSecTuc": "Join CyberSecTuc", "Abrir DedSec": "Open DedSec", "Espacio donde modero junto a la comunidad de": "A space I moderate with the community of", "y sigo aprendiendo con otras personas.": "where I keep learning with others.",
  "Hoy mejor que ayer, mañana mejor que hoy": "Better today than yesterday, better tomorrow than today",
  "Docker local": "Local Docker", "HTML + navegador": "HTML + browser", "Linux local": "Local Linux",
  "Proxy de papel": "Paper proxy", "Logs con memoria": "Memory logs", "Permisos visibles": "Visible permissions",
  "Relacionado con Header trace": "Related to Header trace", "Relacionado con Packet notes": "Related to Packet notes",
  "HACK THE BOX": "HACK THE BOX", "ENTREGA": "DELIVERY", "ARTEFACTO": "ARTIFACT", "Objetivo verificable": "Verifiable objective", "Publicación segura": "Safe publishing",
  "Hola, contenedor": "Hello, container", "Reto de arranque para probar descarga, ejecución aislada y envío de una flag.": "A starter challenge to practice downloading, isolated execution and submitting a flag.", "Identificar una validación defectuosa dentro de una aplicación que controlás.": "Identify a flawed validation in an application you control.", "Header trace": "Header trace", "Seguimiento de confianza entre proxy, aplicación y navegador en un entorno cerrado.": "Trace trust between proxy, application and browser in a closed environment.", "Reconstruir el recorrido de una cabecera dentro de un entorno local.": "Reconstruct a header's path inside a local environment.", "Packet notes": "Packet notes", "Anomalías pequeñas en una captura deliberadamente acotada y navegable en local.": "Small anomalies in a deliberately scoped capture you can inspect locally.", "Encontrar el primer indicador verificable sin automatizar a ciegas.": "Find the first verifiable indicator without blind automation.", "Shell shape": "Shell shape", "Ejercicio de permisos, rutas y supuestos operativos para un host desechable.": "An exercise in permissions, paths and operational assumptions for a disposable host.", "Explicar la cadena de impacto en un informe breve.": "Explain the impact chain in a short report.",
  "Núcleo personal para investigación, práctica, documentación y recursos.": "A personal hub for research, practice, documentation and resources.", "Proyecto de ejemplo para visualizar relaciones entre cabeceras, proxys y servicios antes de crear la herramienta real.": "A seed project to visualize relationships between headers, proxies and services before building the real tool.", "Contrato mínimo para publicar laboratorios locales con alcance, requisitos y forma de limpiar el entorno.": "A minimal contract for publishing local labs with scope, requirements and cleanup steps.", "Estructura de notas para conservar decisiones, pruebas y mitigaciones sin perder el contexto.": "A note structure for preserving decisions, tests and mitigations without losing context.",
  "Una comunidad local de tecnología y ciberseguridad que construimos para acercar formación, charlas, talleres y oportunidades.": "A local technology and cybersecurity community we built to bring training, talks, workshops and opportunities closer.", "Un espacio donde sigo aprendiendo junto a otras personas.": "A space where I keep learning alongside others.", "Aprender": "Learn", "Practicar": "Practice", "Investigar": "Research", "Defender": "Defend", "Compartir": "Share", "Comunidad abierta": "Open community", "Laboratorios guiados": "Guided labs", "Calendario": "Calendar", "Plataforma": "Platform", "Blue team": "Blue team", "Repositorio": "Repository", "Abrir recurso": "Open resource", "Todos": "All", "Fáciles": "Easy", "Medios": "Medium", "Difíciles": "Hard", "Insanos": "Insane", "entradas en el archivo": "entries in the archive", "Buscar writeups": "Search writeups", "Filtrar por dificultad": "Filter by difficulty", "Filtrar desafíos": "Filter challenges"
};

const entries = Object.entries({ ...resources.en.translation, ...englishText }).sort(([left], [right]) => right.length - left.length);

/** Traduce la respuesta HTML antes de enviarla: no requiere JavaScript en el navegador. */
export const translatePage = (html: string) => entries.reduce(
  (translated, [from, to]) => translated.split(from).join(to),
  html.replace('<html lang="es">', '<html lang="en">')
);
