version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-non-breaking:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: bundler
    directory: "/apps/blog"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      bundler-non-breaking:
        update-types:
          - "minor"
          - "patch"
