title: c4cker
tagline: Seguridad aplicada
description: Notas técnicas sobre pentesting, laboratorios y seguridad aplicada.
url: "https://blog.c4cker.com"
baseurl: ""
lang: es-AR
timezone: America/Argentina/Buenos_Aires

github:
  username: c4cker

social:
  name: Luciano Plaza
  email: luciano@koga.ar
  links:
    - https://github.com/c4cker
    - https://www.linkedin.com/in/luciano-matias-plaza-silva

avatar: /assets/img/avatar.jpg

theme: jekyll-theme-chirpy

paginate: 10

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: development

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
