title: c4cker
tagline: Seguridad aplicada
description: Notas técnicas sobre pentesting, laboratorios y seguridad aplicada.
url: "https://blog.c4cker.com"
baseurl: ""
lang: es-AR
timezone: America/Argentina/Buenos_Aires

github:
  username: c4cker

social:
  name: Luciano Plaza
  email: luciano@koga.ar
  links:
    - https://github.com/c4cker
    - https://www.linkedin.com/in/luciano-matias-plaza-silva

avatar: /assets/img/avatar.jpg

theme: jekyll-theme-chirpy

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
      comments: false
      toc: true
  - scope:
      type: tabs
    values:
      layout: page
      permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: development

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
